## Sklearn- A mchine learnign package in Python

- Scikit-learn or sklearn is the most popular package for machine learning.
- It provides a range of machine leraning tools such as classification, regression, clustering and dimensionality reduction through a easy API in python.
- The dependency of this library are NumPy, SciPy and Matplotlib.

### Little bit history of SKlearn
- A product of google summer code project in 2007 by David Cournapeau
- later contibuted by many people (can be seen in its github page)
- [clik here for github](https://github.com/scikit-learn/scikit-learn)

### Installation
` pip install -U scikit-learn`
or 
` Conda install scikit-learn`


## Supported tasks
- Supervised Learning algorithms
    - Linear Regression
    - Support Vector Machine (SVM), 
    - Decision Tree etc.

- Unsupervised Learning algorithms
 - clustering, 
 - factor analysis,
- PCA (Principal Component Analysis) etc.

- Cross Validation
- Dimensionality Reduction
- Feature Selections
- Ensemble methods

For more informations visit documentations [here](https://scikit-learn.org/stable/user_guide.html)

## Machine Learning steps or Pipeline
- data loading
- data preparations
- data cleaning
- Train- test split
- Model Training
- Hyper- parameter tunning
- Model Testing
- Model deployment


 *(All these steps are shown in figure 1 below and supported by SK-Learn)*

<img style="float:center; width:500px" src="../img/Machine-learning-pipeline.png"/>

## lets do it step by step in SKlearn

In [8]:
### Data set loading - C0de taken from Sklearn
from sklearn.datasets import load_iris # toy dataset in sklearn
iris = load_iris() # call actual load iris data fucntion

In [15]:
X = iris.data
y = iris.target
feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names:", feature_names)
print("Target names:", target_names)

Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']


In [16]:
# print first five data samples
X[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [24]:
import numpy as np
print(np.count_nonzero(y == 2))
np.count_nonzero(y==1)

50


50

In [29]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [33]:
X[1]

array([4.9, 3. , 1.4, 0.2])

**For the sake of simiplicity, we are skipping data preprocessing, otherwise we need to perform data preprocessing task in real-world applications**

In [37]:
## Data spliting- Train and Test set

from sklearn.datasets import load_iris
iris = load_iris()

X = iris.data # this is the X or predicator variable for our model
y = iris.target # this is the  y or target variable 

from sklearn.model_selection import train_test_split  # this function do the spliting of full data set into two: train and test

X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size = 0.1, random_state = 1
)

print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(135, 4)
(15, 4)
(135,)
(15,)


In [35]:
# X and Y into two subset: X is divided into train and test similarly y is aslo divided into train and test
X_test.shape, X_train.shape, y_test.shape, y_train.shape

((45, 4), (105, 4), (45,), (105,))